- name: Terraform and Ansible Integration
  hosts: all
  become: true
  
  tasks:
    - name: Copy file to remote server
      copy:
        src: /Users/admin/Desktop/veritas/Project /prathamesh.txt
        dest: /prathamesh/