vpc_cidr_block = "10.0.0.0/16"
subnet_cidr_block="10.0.0.0/24"
avail_zone="ap-south-1a"
env_prefix="dev"
my_ip = "152.57.182.146/32"
instance_type = "t2.micro"
image="amzn2-ami-hvm-*-x86_64-gp2"
private_key_aws = "/Users/admin/Desktop/veritas/Terraform/server-key-pair.pem"

private_key_location = "~/.ssh/id_rsa"
public_key_location = "~/.ssh/id_rsa.pub"