- name: Terraform and Ansible Integration
  hosts: all
  
  tasks:
    - name: Install MongoDB
      become: yes
      apt:
        name: mongodb
        state: present
        update_cache: yes
