---
- name: Terraform Ansible Integration
  hosts: all

  tasks:
    - name:  Install Choclatey
      win_command: powershell.exe Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))

    - name: Set Notepad++ Version
      set_fact:
        version: 7.5.4

    - name: Installing Notepad++
      win_package:
        path: "https://notepad-plus-plus.org/repository/7.x/{{ version }}/npp.{{ version }}.Installer.x64.exe"
        arguments: "/S"
        creates_version: "7.54"
        creates_path: 'C:\Program Files\Notepad++\notepad++.exe'
        state: present
      when: ansible_os_family == 'Windows'

    - name: Add Notepad++ to Path Variable on Windows hosts
      win_path:
        elements:
          - 'C:\Program Files\Notepad++'
      when: ansible_os_family == 'Windows'

    - name: Install Google Chrome
      win_chocolatey:
        name: googlechrome
        state: present
        ignore_checksums: yes
    
    - name: Install python for sure
      win_command: choco install -y python3
    
    - name: Add Python to Path Variable on Windows hosts
      win_path:
        elements:
          - 'C:\Python310'
      when: ansible_os_family == 'Windows'
