---
- name: Terraform Ansible Integration
  hosts: all

  tasks:
    - name: Install chocolatey
      win_chocolatey:
        name:
          - chocolatey
          - chocolatey-core.extension
        state: present
    - name: Installing Notepad++
      win_chocolatey:
        name: notepadplusplus
        version: '7.5.4'    